#!/bin/bash
# build-java-demo.sh — Build and run the Java FFI demo with correct paths
#
# Usage:
#   ./build-java-demo.sh              # build + run demo
#   ./build-java-demo.sh --build-only # build only, don't run
#   ./build-java-demo.sh --run-only   # run demo (assumes already built)
#
# Prerequisites:
#   - JDK installed (set JAVA_HOME or auto-detected)
#   - Rust toolchain

set -e

# ── Detect repo root ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
cd "$REPO_ROOT"

# ── Auto-detect JAVA_HOME ────────────────────────────────────────
if [ -z "$JAVA_HOME" ]; then
    # Try common locations
    for candidate in \
        /usr/lib/jvm/java-25-openjdk \
        /usr/lib/jvm/java-17-openjdk \
        /usr/lib/jvm/java-11-openjdk \
        /usr/lib/jvm/default-java \
        /usr/lib/jvm/java; do
        if [ -d "$candidate" ] && [ -x "$candidate/bin/javac" ]; then
            export JAVA_HOME="$candidate"
            echo "Auto-detected JAVA_HOME=$JAVA_HOME"
            break
        fi
    done
fi

if [ -z "$JAVA_HOME" ]; then
    echo "ERROR: JAVA_HOME not set and could not be auto-detected."
    echo "Set JAVA_HOME to your JDK installation, e.g.:"
    echo "  export JAVA_HOME=/usr/lib/jvm/java-17-openjdk"
    exit 1
fi

if [ ! -x "$JAVA_HOME/bin/javac" ]; then
    echo "ERROR: javac not found in \$JAVA_HOME/bin"
    echo "JAVA_HOME=$JAVA_HOME"
    exit 1
fi

echo "Using JAVA_HOME=$JAVA_HOME"

# ── Build the Java bridge ────────────────────────────────────────
echo ""
echo "=== Building libapl_java.so ==="
JAVA_HOME="$JAVA_HOME" cargo build -p apl-java --features java 2>&1

SO_PATH="$REPO_ROOT/target/debug/libapl_java.so"
if [ ! -f "$SO_PATH" ]; then
    echo "ERROR: libapl_java.so not found at $SO_PATH"
    exit 1
fi
echo "Built: $SO_PATH"

# ── Compile AplUtils.java ────────────────────────────────────────
echo ""
echo "=== Compiling AplUtils.java ==="
cd "$REPO_ROOT/examples"
"$JAVA_HOME/bin/javac" AplUtils.java
echo "Compiled: AplUtils.class"

# ── Generate demo script with correct paths ─────────────────────
echo ""
echo "=== Generating java-demo-sh.apl ==="
cd "$REPO_ROOT"

cat > examples/java-demo-sh.apl << EOF
⍝ Java FFI Demo: Calling Java from APL via JNI bridge
⍝ Demonstrates both standard library and custom class calls
⍝
⍝ Prerequisites:
⍝   1. Build libapljava.so: JAVA_HOME=/path/to/jdk cargo build -p apl-java --features java
⍝   2. Compile AplUtils.java: javac AplUtils.java
⍝
⍝ Run: JAVA_HOME=/path/to/jdk ./target/debug/apl < examples/java-demo-sh.apl
⍝
⍝ This file is auto-generated by build-java-demo.sh — do not edit manually.

⎕IO←1

⍝ === Load the JNI bridge ===
'JI' ⎕NA 'P $SO_PATH|j_init <0T'
'JN' ⎕NA 'P $SO_PATH|j_new <0T'
'JC' ⎕NA 'I4 $SO_PATH|j_call P <0T <0T I8 I8 >I8'
'JCS' ⎕NA 'I4 $SO_PATH|j_call_s P <0T <0T <I4 >0C[256]'
'JS' ⎕NA 'I4 $SO_PATH|j_call_static <0T <0T <0T <0T <I4 >0C[256]'
'JF' ⎕NA 'I4 $SO_PATH|j_free P'
'JG' ⎕NA 'I4 $SO_PATH|j_get_field P <0T <0T >I8'
'JSF' ⎕NA 'I4 $SO_PATH|j_set_field P <0T <0T I8'

⍝ === Initialize JVM (classpath = directory containing .class files) ===
jptr ← JI '$REPO_ROOT/examples'

⍝ === Static method calls (String -> String) ===
⎕ ← 'Calling java.lang.System.getProperty...'
r ← JS ('java/lang/System' 'getProperty' '(Ljava/lang/String;)Ljava/lang/String;' 'java.version' 256)
⎕ ← 'Java version: ',⊃2⊃r

⎕ ← 'Calling custom AplUtils class...'
r ← JS ('AplUtils' 'reverse' '(Ljava/lang/String;)Ljava/lang/String;' 'hello' 256)
⎕ ← 'Reverse "hello": ',⊃2⊃r

r ← JS ('AplUtils' 'isPalindrome' '(Ljava/lang/String;)Z' 'racecar' 256)
⎕ ← 'Is "racecar" palindrome: ',⊃2⊃r

r ← JS ('AplUtils' 'isPalindrome' '(Ljava/lang/String;)Z' 'hello' 256)
⎕ ← 'Is "hello" palindrome: ',⊃2⊃r

r ← JS ('AplUtils' 'sha256' '(Ljava/lang/String;)Ljava/lang/String;' 'hello' 256)
⎕ ← 'SHA−256 of "hello": ',⊃2⊃r

r ← JS ('AplUtils' 'base64Encode' '(Ljava/lang/String;)Ljava/lang/String;' 'hello world' 256)
⎕ ← 'Base64 encode "hello world": ',⊃2⊃r

r ← JS ('AplUtils' 'rot13' '(Ljava/lang/String;)Ljava/lang/String;' 'hello world' 256)
⎕ ← 'ROT13 "hello world": ',⊃2⊃r

r ← JS ('AplUtils' 'uuid' '(I)Ljava/lang/String;' '0' 256)
⎕ ← 'UUID: ',⊃2⊃r

r ← JS ('AplUtils' 'sortCsv' '(Ljava/lang/String;)Ljava/lang/String;' 'c,a,b' 256)
⎕ ← 'Sort CSV "c,a,b": ',⊃2⊃r

r ← JS ('AplUtils' 'wordCount' '(Ljava/lang/String;)Ljava/lang/String;' 'hello world from APL' 256)
⎕ ← 'Word count: ',⊃2⊃r

r ← JS ('AplUtils' 'levenshtein' '(Ljava/lang/String;)Ljava/lang/String;' 'kitten,sitting' 256)
⎕ ← 'Levenshtein "kitten","sitting": ',⊃2⊃r

r ← JS ('AplUtils' 'lcs' '(Ljava/lang/String;)Ljava/lang/String;' 'ABCBDAB,BDCABA' 256)
⎕ ← 'LCS "ABCBDAB","BDCABA": ',⊃2⊃r

⎕ ← 'Java FFI demo complete!'
EOF

echo "Generated: examples/java-demo-sh.apl"

# ── Run the demo ─────────────────────────────────────────────────
if [[ "$*" == *"--build-only"* ]]; then
    echo ""
    echo "=== Build complete. Skipping run (--build-only) ==="
    echo "Run with: ./target/debug/apl < examples/java-demo-sh.apl"
    exit 0
fi

echo ""
echo "=== Running Java FFI demo ==="
echo ""
./target/debug/apl < examples/java-demo-sh.apl
