[package]
name = "apl"
version = "2.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[workspace]
members = ["crates/apl-ext", "crates/demo-plugin", "crates/apl-java", "crates/apl-unofficial"]

[dependencies]
rayon = "1.10"
smallvec = { version = "1.13", features = ["union"] }
libloading = "0.8"
libc = "0.2"
rand = "0.8"
regex = "1.10"
plotters = "0.3"
image = "0.25"
rustfft = "6.2"
rusqlite = "0.31"
apl-ext = { path = "crates/apl-ext" }
apl-unofficial = { path = "crates/apl-unofficial", optional = true }

[features]
default = []
unofficial-ext = ["dep:apl-unofficial"]
plugin-plot = []
plugin-png = []
plugin-sql = []
plugin-fft = []
plugin-python = []
plugin-gtk = []
plugin-cdr = []
plugins = ["plugin-plot", "plugin-png", "plugin-sql", "plugin-fft", "plugin-python", "plugin-gtk", "plugin-cdr"]

[build-dependencies]
toml = "0.8"

[profile.release]
opt-level = 3
lto = true
panic = "unwind"
